language: generic
dist: trusty
addons:
  apt:
    packages:
      - openjdk-7-jdk
      - python3.4-dev
      - python3.4-venv
env:
  - ACTIVATOR_VERSION=1.3.12
before_script:
  - wget https://downloads.typesafe.com/typesafe-activator/${ACTIVATOR_VERSION}/typesafe-activator-${ACTIVATOR_VERSION}-minimal.zip
  - unzip -q typesafe-activator-${ACTIVATOR_VERSION}-minimal.zip
  - python3 -m venv --system-site-packages ./venv
  - . ./venv/bin/activate
  - python3 -m pip install --upgrade pip setuptools
  - pip install WeasyPrint
script:
  - yes "q" | activator-${ACTIVATOR_VERSION}-minimal/bin/activator test
notifications:
  email:
    on_success: change
    on_failure: always
