language: generic
dist: trusty
addons:
  apt:
    packages:
      - openjdk-7-jdk
      - python3.4-dev
      - python3.4-venv
env:
  - PLAY_VERSION=2.2.1
before_script:
  - wget http://downloads.typesafe.com/play/${PLAY_VERSION}/play-${PLAY_VERSION}.zip
  - unzip -q play-${PLAY_VERSION}.zip
  - python3 -m venv --system-site-packages ./venv
  - . ./venv/bin/activate
  - python3 -m pip install --upgrade pip setuptools
  - pip install WeasyPrint
script:
  - yes "q" | play-${PLAY_VERSION}/play jacoco:cover coveralls
  - curl -v --form json_file=@target/coveralls.json https://coveralls.io/api/v1/jobs || true
notifications:
  email:
    recipients:
      - t.dettrick@uq.edu.au
      - a.gebers@uq.edu.au
    on_success: change
    on_failure: always
