language: generic
sudo: required
dist: trusty
addons:
  apt:
    packages:
      - openjdk-7-jdk
      - python3.4-dev
      - python3.4-venv
      - xz-utils
services:
  - docker
env:
  - DOCKER2ACI_VERSION=0.17.0 ACTIVATOR_VERSION=1.3.12
before_script:
  - wget https://downloads.typesafe.com/typesafe-activator/${ACTIVATOR_VERSION}/typesafe-activator-${ACTIVATOR_VERSION}-minimal.zip
  - unzip -q typesafe-activator-${ACTIVATOR_VERSION}-minimal.zip
  - python3 -m venv --system-site-packages ./venv
  - . ./venv/bin/activate
  - python3 -m pip install --upgrade pip setuptools
  - pip install WeasyPrint
script:
  - yes "q" | activator-${ACTIVATOR_VERSION}-minimal/bin/activator test
after_success:
  - curl -sL https://github.com/appc/docker2aci/releases/download/v${DOCKER2ACI_VERSION}/docker2aci-v${DOCKER2ACI_VERSION}.tar.gz | tar xvz --strip-components=1
  - activator-${ACTIVATOR_VERSION}-minimal/bin/activator dist
  - PATH=$PATH:./activator-${ACTIVATOR_VERSION}-minimal/bin:. ./build_aci.sh
  - xz aorra.docker
notifications:
  email:
    on_success: change
    on_failure: always
deploy:
  provider: releases
  api_key:
    secure: "IaFNGkTBBEBOduhhO/Bsic5Y19Avf129b1T7TVGeDdsffno4R4+0yhoCQClfZQQN9mHWKexrRA3j6D//gDYn6D38uQ/myuS7PYhxs0DPSQ/fyILHprNkl9dpo2tJaQy2jzjYxBoNVLcK9rj2sVIXqqzCmxIGxnM9dr9RUd/rLR8="
  file:
    - aorra.aci
    - aorra.docker.xz
  skip_cleanup: true
  on:
    tags: true
    repo: dit4c/dockerfile-nghttpx
