language: generic
dist: trusty
addons:
  apt:
    sources:
      - sourceline: "deb https://dl.bintray.com/sbt/debian /"
        key_url: "http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823"
    packages:
      - openjdk-7-jdk
      - sbt
      - python3.4-dev
      - python3.4-venv
before_script:
  - python3 -m venv --system-site-packages ./venv
  - . ./venv/bin/activate
  - python3 -m pip install --upgrade pip setuptools
  - pip install WeasyPrint
script:
  - yes "q" | sbt jacoco:cover coveralls
  - curl -v --form json_file=@target/coveralls.json https://coveralls.io/api/v1/jobs || true
notifications:
  email:
    recipients:
      - t.dettrick@uq.edu.au
      - a.gebers@uq.edu.au
    on_success: change
    on_failure: always
